name: flutter_google_books
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  flutter: ^3.38.5
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  json_theme: ^11.0.0
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  http: ^1.6.0
  get_it: ^9.2.0
  injectable: ^2.7.1+2
  json_annotation: ^4.9.0
  flutter_hooks: ^0.21.3+1
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  another_flushbar: ^1.12.32

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  json_serializable: ^6.10.4
  injectable_generator: ^2.9.1

flutter:
  uses-material-design: true

  assets:
    - assets/appainter_theme.json
    - assets/images/